module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Praa.fna  --outdir ~/work/Zhang/Prokka/Praa --compliant --addgenes --prefix Praa --locustag Praa.g --genus Prochlorococcus --species "Prochlorococcus marinus" --strain "AS9601" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Prab.fna  --outdir ~/work/Zhang/Prokka/Prab --compliant --addgenes --prefix Prab --locustag Prab.g --genus Prochlorococcus --species "Prochlorococcus marinus" --strain "MED4" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Prac.fna  --outdir ~/work/Zhang/Prokka/Prac --compliant --addgenes --prefix Prac --locustag Prac.g --genus Prochlorococcus --species "Prochlorococcus marinus" --strain "MIT 9107" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Prad.fna  --outdir ~/work/Zhang/Prokka/Prad --compliant --addgenes --prefix Prad --locustag Prad.g --genus Prochlorococcus --species "Prochlorococcus marinus" --strain "MIT 9201" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Prae.fna  --outdir ~/work/Zhang/Prokka/Prae --compliant --addgenes --prefix Prae --locustag Prae.g --genus Prochlorococcus --species "Prochlorococcus marinus" --strain "MIT 9301" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Praf.fna  --outdir ~/work/Zhang/Prokka/Praf --compliant --addgenes --prefix Praf --locustag Praf.g --genus Prochlorococcus --species "Prochlorococcus marinus" --strain "MIT 9303" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Prag.fna  --outdir ~/work/Zhang/Prokka/Prag --compliant --addgenes --prefix Prag --locustag Prag.g --genus Prochlorococcus --species "Prochlorococcus marinus" --strain "MIT 9312" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Prah.fna  --outdir ~/work/Zhang/Prokka/Prah --compliant --addgenes --prefix Prah --locustag Prah.g --genus Prochlorococcus --species "Prochlorococcus marinus" --strain "MIT9313" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Prai.fna  --outdir ~/work/Zhang/Prokka/Prai --compliant --addgenes --prefix Prai --locustag Prai.g --genus Prochlorococcus --species "Prochlorococcus marinus" --strain "MIT 9515" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Praj.fna  --outdir ~/work/Zhang/Prokka/Praj --compliant --addgenes --prefix Praj --locustag Praj.g --genus Prochlorococcus --species "Prochlorococcus marinus" --strain "NATL2A" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Prak.fna  --outdir ~/work/Zhang/Prokka/Prak --compliant --addgenes --prefix Prak --locustag Prak.g --genus Prochlorococcus --species "Prochlorococcus marinus" --strain "CCMP1375; SS120" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Pral.fna  --outdir ~/work/Zhang/Prokka/Pral --compliant --addgenes --prefix Pral --locustag Pral.g --genus Prochlorococcus --species "Prochlorococcus sp." --strain "MIT 0601" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Pram.fna  --outdir ~/work/Zhang/Prokka/Pram --compliant --addgenes --prefix Pram --locustag Pram.g --genus Prochlorococcus --species "Prochlorococcus sp." --strain "MIT 0603" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Pran.fna  --outdir ~/work/Zhang/Prokka/Pran --compliant --addgenes --prefix Pran --locustag Pran.g --genus Prochlorococcus --species "Prochlorococcus marinus" --strain "EQPAC1" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Prao.fna  --outdir ~/work/Zhang/Prokka/Prao --compliant --addgenes --prefix Prao --locustag Prao.g --genus Prochlorococcus --species "Prochlorococcus marinus" --strain "GP2" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Prap.fna  --outdir ~/work/Zhang/Prokka/Prap --compliant --addgenes --prefix Prap --locustag Prap.g --genus Prochlorococcus --species "Prochlorococcus marinus" --strain "LG" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Praq.fna  --outdir ~/work/Zhang/Prokka/Praq --compliant --addgenes --prefix Praq --locustag Praq.g --genus Prochlorococcus --species "Prochlorococcus marinus" --strain "MIT 9116" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Prar.fna  --outdir ~/work/Zhang/Prokka/Prar --compliant --addgenes --prefix Prar --locustag Prar.g --genus Prochlorococcus --species "Prochlorococcus marinus" --strain "MIT 9123" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Pras.fna  --outdir ~/work/Zhang/Prokka/Pras --compliant --addgenes --prefix Pras --locustag Pras.g --genus Prochlorococcus --species "Prochlorococcus marinus" --strain "MIT 9202" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Prat.fna  --outdir ~/work/Zhang/Prokka/Prat --compliant --addgenes --prefix Prat --locustag Prat.g --genus Prochlorococcus --species "Prochlorococcus marinus" --strain "MIT 9211" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Prau.fna  --outdir ~/work/Zhang/Prokka/Prau --compliant --addgenes --prefix Prau --locustag Prau.g --genus Prochlorococcus --species "Prochlorococcus marinus" --strain "MIT 9215" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Prav.fna  --outdir ~/work/Zhang/Prokka/Prav --compliant --addgenes --prefix Prav --locustag Prav.g --genus Prochlorococcus --species "Prochlorococcus marinus" --strain "MIT 9302" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Praw.fna  --outdir ~/work/Zhang/Prokka/Praw --compliant --addgenes --prefix Praw --locustag Praw.g --genus Prochlorococcus --species "Prochlorococcus marinus" --strain "MIT 9311" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Prax.fna  --outdir ~/work/Zhang/Prokka/Prax --compliant --addgenes --prefix Prax --locustag Prax.g --genus Prochlorococcus --species "Prochlorococcus marinus" --strain "MIT 9314" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Pray.fna  --outdir ~/work/Zhang/Prokka/Pray --compliant --addgenes --prefix Pray --locustag Pray.g --genus Prochlorococcus --species "Prochlorococcus marinus" --strain "MIT 9321" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Praz.fna  --outdir ~/work/Zhang/Prokka/Praz --compliant --addgenes --prefix Praz --locustag Praz.g --genus Prochlorococcus --species "Prochlorococcus marinus" --strain "MIT 9322" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Prba.fna  --outdir ~/work/Zhang/Prokka/Prba --compliant --addgenes --prefix Prba --locustag Prba.g --genus Prochlorococcus --species "Prochlorococcus marinus" --strain "MIT 9401" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Prbb.fna  --outdir ~/work/Zhang/Prokka/Prbb --compliant --addgenes --prefix Prbb --locustag Prbb.g --genus Prochlorococcus --species "Prochlorococcus marinus" --strain "NATL1A" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Prbc.fna  --outdir ~/work/Zhang/Prokka/Prbc --compliant --addgenes --prefix Prbc --locustag Prbc.g --genus Prochlorococcus --species "Prochlorococcus marinus" --strain "PAC1" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Prbd.fna  --outdir ~/work/Zhang/Prokka/Prbd --compliant --addgenes --prefix Prbd --locustag Prbd.g --genus Prochlorococcus --species "Prochlorococcus marinus" --strain "SB" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Prbe.fna  --outdir ~/work/Zhang/Prokka/Prbe --compliant --addgenes --prefix Prbe --locustag Prbe.g --genus Prochlorococcus --species "Prochlorococcus marinus" --strain "SS2" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Prbf.fna  --outdir ~/work/Zhang/Prokka/Prbf --compliant --addgenes --prefix Prbf --locustag Prbf.g --genus Prochlorococcus --species "Prochlorococcus marinus" --strain "SS35" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Prbg.fna  --outdir ~/work/Zhang/Prokka/Prbg --compliant --addgenes --prefix Prbg --locustag Prbg.g --genus Prochlorococcus --species "Prochlorococcus marinus" --strain "SS51" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Prbh.fna  --outdir ~/work/Zhang/Prokka/Prbh --compliant --addgenes --prefix Prbh --locustag Prbh.g --genus Prochlorococcus --species "Prochlorococcus sp." --strain "MIT 0602" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Prbi.fna  --outdir ~/work/Zhang/Prokka/Prbi --compliant --addgenes --prefix Prbi --locustag Prbi.g --genus Prochlorococcus --species "Prochlorococcus sp." --strain "MIT 0604" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Prbj.fna  --outdir ~/work/Zhang/Prokka/Prbj --compliant --addgenes --prefix Prbj --locustag Prbj.g --genus Prochlorococcus --species "Prochlorococcus sp." --strain "MIT 0701" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Prbk.fna  --outdir ~/work/Zhang/Prokka/Prbk --compliant --addgenes --prefix Prbk --locustag Prbk.g --genus Prochlorococcus --species "Prochlorococcus sp." --strain "MIT 0702" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Prbl.fna  --outdir ~/work/Zhang/Prokka/Prbl --compliant --addgenes --prefix Prbl --locustag Prbl.g --genus Prochlorococcus --species "Prochlorococcus sp." --strain "MIT 0703" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Prbm.fna  --outdir ~/work/Zhang/Prokka/Prbm --compliant --addgenes --prefix Prbm --locustag Prbm.g --genus Prochlorococcus --species "Prochlorococcus sp." --strain "MIT 0801" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Prbn.fna  --outdir ~/work/Zhang/Prokka/Prbn --compliant --addgenes --prefix Prbn --locustag Prbn.g --genus Prochlorococcus --species "Prochlorococcus sp." --strain "SS52" --kingdom Bacteria --cpus 1
