module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Syaa.fna  --outdir ~/work/Zhang/Prokka/Syaa --compliant --addgenes --prefix Syaa --locustag Syaa.g --genus Synechococcus --species "Parasynechococcus marenigrum" --strain "WH 8102" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Syab.fna  --outdir ~/work/Zhang/Prokka/Syab --compliant --addgenes --prefix Syab --locustag Syab.g --genus Synechococcus --species "Synechococcus sp." --strain "CC9311" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Syac.fna  --outdir ~/work/Zhang/Prokka/Syac --compliant --addgenes --prefix Syac --locustag Syac.g --genus Synechococcus --species "Synechococcus sp." --strain "CC9902" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Syad.fna  --outdir ~/work/Zhang/Prokka/Syad --compliant --addgenes --prefix Syad --locustag Syad.g --genus Synechococcus --species "Synechococcus sp." --strain "KORDI 100" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Syae.fna  --outdir ~/work/Zhang/Prokka/Syae --compliant --addgenes --prefix Syae --locustag Syae.g --genus Synechococcus --species "Synechococcus sp." --strain "KORDI 49" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Syaf.fna  --outdir ~/work/Zhang/Prokka/Syaf --compliant --addgenes --prefix Syaf --locustag Syaf.g --genus Synechococcus --species "Synechococcus sp." --strain "KORDI 52" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Syag.fna  --outdir ~/work/Zhang/Prokka/Syag --compliant --addgenes --prefix Syag --locustag Syag.g --genus Synechococcus --species "Synechococcus sp." --strain "RS9916" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Syah.fna  --outdir ~/work/Zhang/Prokka/Syah --compliant --addgenes --prefix Syah --locustag Syah.g --genus Synechococcus --species "Synechococcus sp." --strain "BL107" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Syai.fna  --outdir ~/work/Zhang/Prokka/Syai --compliant --addgenes --prefix Syai --locustag Syai.g --genus Synechococcus --species "Synechococcus sp." --strain "CC9605" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Syaj.fna  --outdir ~/work/Zhang/Prokka/Syaj --compliant --addgenes --prefix Syaj --locustag Syaj.g --genus Synechococcus --species "Synechococcus sp." --strain "CC9616" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Syak.fna  --outdir ~/work/Zhang/Prokka/Syak --compliant --addgenes --prefix Syak --locustag Syak.g --genus Synechococcus --species "Synechococcus sp." --strain "WH 7805" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Syal.fna  --outdir ~/work/Zhang/Prokka/Syal --compliant --addgenes --prefix Syal --locustag Syal.g --genus Synechococcus --species "Synechococcus sp." --strain "WH 8016" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Syam.fna  --outdir ~/work/Zhang/Prokka/Syam --compliant --addgenes --prefix Syam --locustag Syam.g --genus Synechococcus --species "Synechococcus sp." --strain "WH 8109" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Syan.fna  --outdir ~/work/Zhang/Prokka/Syan --compliant --addgenes --prefix Syan --locustag Syan.g --genus Synechococcus --species "Synechococcus sp." --strain "CB0101" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Syao.fna  --outdir ~/work/Zhang/Prokka/Syao --compliant --addgenes --prefix Syao --locustag Syao.g --genus Synechococcus --species "Synechococcus sp." --strain "CB0205" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Syap.fna  --outdir ~/work/Zhang/Prokka/Syap --compliant --addgenes --prefix Syap --locustag Syap.g --genus Synechococcus --species "Synechococcus sp." --strain "GFB01" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Syaq.fna  --outdir ~/work/Zhang/Prokka/Syaq --compliant --addgenes --prefix Syaq --locustag Syaq.g --genus Synechococcus --species "Synechococcus sp." --strain "RS9917; RCC556" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Syar.fna  --outdir ~/work/Zhang/Prokka/Syar --compliant --addgenes --prefix Syar --locustag Syar.g --genus Synechococcus --species "Synechococcus sp." --strain "WH 5701" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Syas.fna  --outdir ~/work/Zhang/Prokka/Syas --compliant --addgenes --prefix Syas --locustag Syas.g --genus Synechococcus --species "Cyanobium sp." --strain "PCC 7001" --kingdom Bacteria --cpus 1
module load bioinfo/PROKKA/1.14.5; prokka  ~/work/Zhang/DNA/Syat.fna  --outdir ~/work/Zhang/Prokka/Syat --compliant --addgenes --prefix Syat --locustag Syat.g --genus Synechococcus --species "Cyanobium gracile" --strain "PCC 6307" --kingdom Bacteria --cpus 1
